version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
    depends_on:
      - dind

volumes:
  jenkins-data:

networks:
  jenkins:
